# Github workflow syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches:
      - main
  # branches-ignore:
  #   - main
  #   - "releases/**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - "releases/**"

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: "--health-cmd='mongo --eval \"db.runCommand({ ping: 1 })\"' --health-interval=10s --health-timeout=5s --health-retries=5"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod download -x

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017
        run: go test -v -p 1 -count=1 -race -cover ./...
