# Github workflow syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches:
      - main
  # branches-ignore:
  #   - main
  #   - "releases/**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - "releases/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['5.0', '6.0']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod download -x

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017
        run: go test -v -p 1 -count=1 -race -cover ./...
